SET C51INC=C:\Keil_v5\C51\Inc;C:\Keil_v5\C51\Inc\Cast
SET C51LIB=C:\Keil_v5\C51\Lib
SET CPU_TYPE=R8051XC2
SET CPU_VENDOR=CAST, Inc.
SET UV2_TARGET=CA51F5
SET CPU_XTAL=0x016E3600
"C:\Keil_v5\C51\BIN\C51.EXE" @.\hex\main.__i
"C:\Keil_v5\C51\BIN\C51.EXE" @.\hex\delay.__i
"C:\Keil_v5\C51\BIN\C51.EXE" @.\hex\SYSTEM~1.__I
"C:\Keil_v5\C51\BIN\C51.EXE" @.\hex\uart.__i
"C:\Keil_v5\C51\BIN\C51.EXE" @.\hex\INTERR~1.__I
"C:\Keil_v5\C51\BIN\C51.EXE" @.\hex\adkey.__i
"C:\Keil_v5\C51\BIN\C51.EXE" @.\hex\debug.__i
"C:\Keil_v5\C51\BIN\C51.EXE" @.\hex\ts_api.__i
"C:\Keil_v5\C51\BIN\A51.EXE" @.\hex\STARTUP._ia
"C:\Keil_v5\C51\BIN\LX51.EXE" @.\hex\ca51fx.lnp
"C:\Keil_v5\C51\BIN\OHX51.EXE" ".\hex\ca51fx" HEX
